variables:
  common:
    environment:    "dev"
    project:        "banana"
    type:           "primary"

  products:
    - name:         "app1.1"
      product:      "product1"
      productType:  "app"
      chart:        "app"
      appVersion:   "1.27.1-alpine-slim"
    - name:         "app1.2"
      product:      "product1"
      productType:  "app"
      chart:        "app"
      appVersion:   "1.27.2-alpine-slim"
    - name:         "app2.1"
      product:      "product2"
      productType:  "app"
      chart:        "app"
      appVersion:   "1.26.1-alpine-slim"
    - name:         "app2.2"
      product:      "product2"
      productType:  "app"
      chart:        "app"
      appVersion:   "1.26.2-alpine-slim"

  infrastructure:
    - name:         "etcd"
      product:      "shared"
      productType:  "infra"
      chart:        "etcd"
      repoUrl:      "registry-1.docker.io/bitnamicharts"
      chartVersion: "10.5.3"
    - name:         "mongodb"
      product:      "shared"
      productType:  "infra"
      chart:        "mongodb"
      repoUrl:      "registry-1.docker.io/bitnamicharts"
      chartVersion: "16.3.0"
